version: '3'

networks:
    test:
services:
    web:
        build: .
        image: php:7.4-apache
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
        networks:
            - test
    mysql:
        image: mysql:5.7.29
        container_name: mysql-php
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: php-test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            SERVICE_NAME: mysql-php
        networks:
            - test

